Pustok/Areas/Admin/Controllers/ProductSliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pustok.DAL;
using Pustok.DAL.Models;

namespace Fiorello.Areas.Admin.Controllers
{
    public class ProductSliderController : Controller
    {
        
        private readonly AppDbContext _context;

        public ProductSliderController(AppDbContext context)
        {
            _context = context;
        }
        // GET
        public IActionResult Index()
        {
            List<Product> products = _context.Products.Where(p => !p.IsDeleted).Include(p => p.Author).ToList();
            return View(products);
        }
        
        public IActionResult Details(int id)
        {
            List<Product> product = _context.Products.Where(p => p.Id == id).Include(p => p.Author).ToList();
            return View(product);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Product product = _context.Products.Where(p => p.Id == id).Include(p => p.Author).FirstOrDefault();
            return View(product);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id,string productName,decimal productCostPrice,decimal productSalePrice,decimal productDiscountPrice)
        {
            Product product = _context.Products.Where(p => p.Id == id).Include(p => p.Author).FirstOrDefault();
            if (product is null || string.IsNullOrEmpty(productName.Trim()))
            {
                return NotFound();
            }
            product.Name = String.Join(" ", productName.Split("+"));
            product.CostPrice = (double)productCostPrice;
            product.SalePrice = (double)productSalePrice;
            product.DiscountPrice = (double)productDiscountPrice;
            _context.Products.Update(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Product product)
        {
            Author author = new Author();
            Category category = new Category();
            author.Fullname = "Adil Valizada";
            category.Name = "Action";
            product.IsFeatured = false;
            product.IsNew = true;
            product.Author = author;
            product.Category = category;
            _context.Products.Add(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Product product = _context.Products.Where(p => p.Id == id).Include(p => p.Author).FirstOrDefault();
            product.IsDeleted = true;
            _context.Products.Update(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Pustok/Areas/Admin/Controllers/SliderController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Pustok.DAL;
using Pustok.DAL.Models;

namespace Fiorello.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        
        private readonly AppDbContext _context;

        public SliderController(AppDbContext context)
        {
            _context = context;
        }
        // GET
        public IActionResult Index()
        {
            List<Slider> sliders = _context.Sliders.Where(s => !s.IsDeleted).ToList();
            return View(sliders);
        }
        
        public IActionResult Details(int id)
        {
            Slider slider = _context.Sliders.FirstOrDefault(s => !s.IsDeleted && s.Id == id);
            return View(slider);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Slider slider = _context.Sliders.FirstOrDefault(s => !s.IsDeleted && s.Id == id);
            slider.IsDeleted = true;
            _context.Sliders.Update(slider);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Update(int id)
        {
            Slider slider = _context.Sliders.FirstOrDefault(s => s.Id == id);
            return View(slider);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id,string title1,string title2,string description,string imageUrl,string redirectText,string redirectUrl)
        {
            Slider slider = _context.Sliders.FirstOrDefault(s => s.Id == id);
            if (slider is null)
            {
                return NotFound();
            }

            slider.Title1 = title1;
            slider.Title2 = title2;
            slider.Description = description;
            slider.ImageUrl = imageUrl;
            slider.RedirectText = redirectText;
            slider.RedirectUrl = redirectUrl;
            _context.Sliders.Update(slider);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Slider slider)
        {
            int order = _context.Sliders.ToList()[_context.Sliders.ToList().Count - 1].Order;
            slider.Order = order + 1;
            _context.Sliders.Add(slider);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Pustok/Areas/Admin/Views/Slider/Create.cshtml
@model Slider

 <div class="container">
     <div class="row">
         <div class="col-12 grid-margin stretch-card">
             <div class="card">
                 <div class="card-body">
                     <form method="post" class="forms-sample">
                         <div class="form-group">
                             <label for="exampleInputUsername1">Title 1</label>
                             <input asp-for="@Model.Title1"  name="title1" class="form-control" id="exampleInputUsername1" placeholder="title 2">
                         </div>
                         <div class="form-group">
                             <label >Title 2</label>
                             <input  name="title2" asp-for="@Model.Title2" class="form-control"  placeholder="title 2">
                         </div>
                         <div class="form-group">
                             <label >Description</label>
                             <input  name="description" asp-for="@Model.Description" class="form-control"  placeholder="description">
                         </div>
                         <div class="form-group">
                             <label >Image Url</label>
                             <input name="imageUrl" asp-for="@Model.ImageUrl" class="form-control"  placeholder="image url">
                         </div>
                         <div class="form-group">
                             <label >Redirect Text</label>
                             <input  name="redirectText" asp-for="@Model.RedirectText" class="form-control"  placeholder="redirect text">
                         </div>
                         <div class="form-group">
                             <label >Redirect Url</label>
                             <input  name="redirectUrl" asp-for="@Model.RedirectUrl" class="form-control"  placeholder="redirect url">
                         </div>
                         <button type="submit" class="btn btn-primary mr-2">Submit</button>
                         <a class="btn btn-light" asp-area="Admin" asp-controller="Slider" asp-action="Index">Cancel</a>
                     </form>
                 </div>
             </div>
         </div>
     </div>
 </div>

Pustok/Areas/Admin/Views/Slider/Details.cshtml
@model Slider

<div class="container">

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="row justify-content-between">
                        <h4 class="card-title">Category Table</h4>
                        <a asp-area="Admin" asp-controller="ProductSlider" asp-action="Create" class="btn btn-success">Create</a>
                        
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>
                                    Id
                                </th>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Title 1
                                </th>
                                
                                <th>
                                   Title 2
                                </th>
                                <th>
                                   Description
                                </th>
                                <th>
                                    Redirect Text
                                </th>
                                <th>
                                    Redirect Url
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                    <td>
                                        @Model.Id
                                    </td>
                                    <td>
                                        <img src="~/assets/image/bg-images/@Model.ImageUrl" alt="">
                                    </td>
                                    <td>
                                        @Model.Title1
                                    </td>
                                    <td>
                                        @Model.Title2
                                    </td>
                                  
                                    <td>
                                        @Model.Description
                                    </td>
                                    
                                    <td>
                                        @Model.RedirectText
                                    </td>
                                    
                                    <td>
                                        @Model.RedirectUrl
                                    </td>
                                    <td class="d-flex flex-column">
                                        <a class="btn btn-warning my-2 ">Update</a>
                                        <form method="post">
                                            <button  class="btn btn-danger my-2" asp-controller="Slider" asp-route-id="@Model.Id">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pustok/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>


<div class="container">

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="row justify-content-between">
                        <h4 class="card-title">Category Table</h4>
                        <a asp-area="Admin" asp-controller="Slider" asp-action="Create" class="btn btn-success">Create</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>
                                    Id
                                </th>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Title 1
                                </th>
                                
                                <th>
                                   Title 2
                                </th>
                                <th>
                                   Description
                                </th>
                                <th>
                                    Redirect Text
                                </th>
                                <th>
                                    Redirect Url
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach (var slider in Model)
                            {
                                <tr>
                                    <td>
                                        @slider.Id
                                    </td>
                                    <td>
                                        <img src="~/assets/image/bg-images/@slider.ImageUrl" alt="">
                                    </td>
                                    <td>
                                        @slider.Title1
                                    </td>
                                    <td>
                                        @slider.Title2
                                    </td>
                                  
                                    <td>
                                        @slider.Description
                                    </td>
                                    
                                    <td>
                                        @slider.RedirectText
                                    </td>
                                    
                                    <td>
                                        @slider.RedirectUrl
                                    </td>
                                    <td class="d-flex flex-column">
                                        <a  class="btn btn-primary my-2" asp-area="Admin" asp-controller="Slider" asp-action="Details" asp-route-id="@slider.Id" >Details</a>
                                        <a class="btn btn-warning my-2" asp-area="Admin" asp-controller="Slider" asp-action="Update" asp-route-id="@slider.Id">Update</a>
                                        <a  class="btn btn-danger my-2" asp-area="Admin" asp-controller="Slider" asp-action="Details" asp-route-id="@slider.Id" >Delete</a>
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pustok/Areas/Admin/Views/Slider/Update.cshtml
@model Slider

<div class="container">
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form method="post" class="forms-sample">
                        <div class="form-group">
                            <label for="exampleInputUsername1">Title 1</label>
                            <input value="@Model.Title1" name="title1" type="text" class="form-control" id="exampleInputUsername1" placeholder="title 2">
                        </div>
                        <div class="form-group">
                            <label >Title 2</label>
                            <input value="@Model.Title2" name="title2" type="text" class="form-control"  placeholder="title 2">
                        </div>
                        <div class="form-group">
                            <label >Description</label>
                            <input value="@Model.Description" name="description" type="text" class="form-control"  placeholder="description">
                        </div>
                        <div class="form-group">
                            <label >Image Url</label>
                            <input value="@Model.ImageUrl" name="imageUrl" type="text" class="form-control"  placeholder="image url">
                        </div>
                        <div class="form-group">
                            <label >Redirect Text</label>
                            <input value="@Model.RedirectText" name="redirectText" type="text" class="form-control"  placeholder="redirect text">
                        </div>
                        <div class="form-group">
                            <label >Redirect Url</label>
                            <input value="@Model.RedirectUrl" name="redirectUrl" type="text" class="form-control"  placeholder="redirect url">
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a class="btn btn-light" asp-area="Admin" asp-controller="Slider" asp-action="Details" asp-route-id="@Model.Id">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>